export const PLAYER_ATTACK = "PLAYER_ATTACK";
export const PLAYER_LOST = "PLAYER_LOST";
export const PLAYER_WON = "PLAYER_WON";
export const AI_ATTACK = "AI_ATTACK";
export const BUILDING_ENEMY_BOARD = "BUILDING_ENEMY_BOARD";
export const BUILDING_PLAYER_BOARD = "BUILDING_PLAYER_BOARD";
export const INITIAL_COIN_FLIP = "INITIAL_COIN_FLIP";
